# Generated by Django 5.1.6 on 2025-02-11 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_review'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='user',
            new_name='username',
        ),
    ]
